steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/revops-486917/gcr.io/panther-dashboard-backend:latest', '-f', 'Dockerfile.gke', '.']
    dir: 'packages/backend'
images:
  - 'us-docker.pkg.dev/revops-486917/gcr.io/panther-dashboard-backend:latest'
