steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/panther-backend:revops-v33', '-f', 'Dockerfile.gke', '.']
    dir: 'packages/backend'
images:
  - 'gcr.io/$PROJECT_ID/panther-backend:revops-v33'
