apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revops

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: frontend-patch.yaml
  - path: backend-patch.yaml

images:
  - name: us-docker.pkg.dev/revops-486917/gcr.io/panther-dashboard-frontend
    newTag: latest
  - name: us-docker.pkg.dev/revops-486917/gcr.io/panther-dashboard-backend
    newTag: latest
