apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panther-dashboard-ingress
  namespace: panther-dashboard
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "panther-dashboard-ip"
    networking.gke.io/managed-certificates: "panther-dashboard-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: panther-dashboard.example.com
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: panther-dashboard-cert
  namespace: panther-dashboard
spec:
  domains:
    - panther-dashboard.example.com
