apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revops

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - migration-job.yaml
  - redis-deployment.yaml
  - pdb.yaml
  - syslog-service.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - frontend-config.yaml
  - iap-backendconfig.yaml
