apiVersion: v1
kind: Service
metadata:
  name: syslog-receiver
  namespace: revops
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: syslog-udp
      port: 5514
      targetPort: 5514
      protocol: UDP
  type: LoadBalancer
